spring:
  profiles:
    active: '@profile.active@'
    include: '@env.PRODUCT@,default'

  data:
    mongodb:
      uri: 'mongodb://127.0.0.1:27017/tapdata?authSource=admin'
      cursorBatchSize: 1000

